export const filmes = [
  {
    id: 1,
    titulo: "Selma",
    slug:"Selma",
    fotoThumbnail: "../Imagens/Filmes-educacionais/SELMA.jpg",
    ano_lancamento: 201,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Histórico",
    elenco: ["David Oyelowo", "Carmen Ejogo", "Tom Wilkinson", "Oprah Winfrey"],
    duracao: "128min",
    nota_avaliacao: 7.5,
    faixa_etaria: "12+",
    indicacoes_premios: ["Oscar", "Globo de Ouro", "BAFTA"],
    sinopse: "Acompanhe a inspiradora marcha liderada por Martin Luther King Jr. de Selma a Montgomery, no Alabama, em 1965. O movimento buscava garantir o direito ao voto para a comunidade negra dos Estados Unidos, enfrentando intensa repressão e violência policial, tornando-se um marco fundamental na luta pelos direitos civis."
  },
  {
    id: 2,
    titulo: "Mãos Talentosas",
    fotoThumbnail: "../Imagens/Filmes-educacionais/TALENTOSAS.webp",
    ano_lancamento: 2013,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Biografia",
    elenco: ["Cuba Gooding Jr.", "Kimberly Elise", "Aunjanue Ellis"],
    duracao: "86min",
    nota_avaliacao: 7.7,
    faixa_etaria: "10+",
    indicacoes_premios: ["Image Awards", "Humanitas Prize"],
    sinopse: "Baseado em uma história real, o filme acompanha a trajetória de Ben Carson, que de uma infância humilde marcada por dificuldades se tornou um dos neurocirurgiões mais renomados do mundo. Sua determinação, fé e dedicação aos estudos transformaram sua vida e inspiraram milhões."
  },
  {
    id: 3,
    titulo: "Cidade de Deus",
    fotoThumbnail: "../Imagens/Filmes-educacionais/CIDADE-DE-DEUS.jpg",
    ano_lancamento: 2002,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Crime",
    elenco: ["Alexandre Rodrigues", "Leandro Firmino", "Phellipe Haagensen", "Douglas Silva"],
    duracao: "130min",
    nota_avaliacao: 8.6,
    faixa_etaria: "16+",
    indicacoes_premios: ["Oscar", "BAFTA", "Globo de Ouro"],
    sinopse: "Inspirado em fatos reais, o filme retrata a ascensão do crime organizado na comunidade Cidade de Deus, no Rio de Janeiro, entre as décadas de 1960 e 1980. A história é contada pela perspectiva de Buscapé, um jovem que sonha em ser fotógrafo, enquanto acompanha a violência, o tráfico e a luta pela sobrevivência em meio à pobreza."
  },
  {
    id: 4,
    titulo: "O Primeiro da Classe",
    slug: "o-primeiro-da-classe",
    fotoThumbnail: "../Imagens/Filmes-educacionais/CLASSE.webp",
    ano_lancamento: 2008,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Biografia",
    elenco: ["James Wolk", "Treat Williams", "Patricia Heaton"],
    duracao: "95min",
    nota_avaliacao: 8.0,
    faixa_etaria: "10+",
    indicacoes_premios: ["Humanitas Prize", "Directors Guild of America Awards"],
    sinopse: "Baseado em uma história real, o filme acompanha Brad Cohen, um jovem diagnosticado com síndrome de Tourette que enfrenta preconceito e dificuldades ao longo da vida. Com perseverança e apoio, ele conquista seu sonho de se tornar professor, inspirando alunos e colegas a superar desafios."
  },
  {
    id: 5,
    titulo: "Extraordinário",
    slug: "extraordinario",
    fotoThumbnail: "../Imagens/Filmes-educacionais/EXTRAORDINARIO.png",
    ano_lancamento: 2017,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Família",
    elenco: ["Jacob Tremblay", "Julia Roberts", "Owen Wilson", "Izabela Vidovic"],
    duracao: "113min",
    nota_avaliacao: 8.0,
    faixa_etaria: "10+",
    indicacoes_premios: ["Critics' Choice Awards", "Art Directors Guild Awards"],
    sinopse: "Auggie Pullman nasceu com uma síndrome genética que causou deformidades faciais e passou por diversas cirurgias. Pela primeira vez frequentando a escola regular, ele precisa lidar com o preconceito e aprender o valor da amizade, da empatia e da aceitação."
  },
];

export const filmes2 = [
  {
    id: 8,
    titulo: "La Casa de Papel",
    fotoThumbnail: "../Imagens/La-Casa-De-Papel-NI.jpg",
    tipo: "s",
    ano_lancamento: 2017,
    genero: "Ação, Crime",
    elenco: ["Álvaro Morte", "Úrsula Corberó"],
    duracao: "50min",
    nota_avaliacao: 8.3,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy Internacional"],
    sinopse: "Um homem misterioso conhecido como 'O Professor' recruta oito pessoas para realizar o maior assalto da história: roubar a Casa da Moeda da Espanha. Enquanto executam o plano, eles precisam lidar com a polícia e reféns."
  },
  {
    id: 10,
    titulo: "Narcos",
    fotoThumbnail: "../Imagens/Narcos-NI.jpg",
    tipo: "s",
    ano_lancamento: 2015,
    genero: "Crime, Drama",
    elenco: ["Wagner Moura", "Pedro Pascal"],
    duracao: "49min",
    nota_avaliacao: 8.8,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy"],
    sinopse: "A série narra a história real da ascensão e queda do infame traficante colombiano Pablo Escobar e do Cartel de Medellín, contada a partir da perspectiva de Escobar e dos agentes do DEA que lideraram a missão para capturá-lo."
  },
];

export const filmesNum = [
  {
    id: 17,
    titulo: "Cobra Kai",
    fotoThumbnail: "../Imagens/Cobra-Kai-NI.jpg",
    tipo: "s",
    ano_lancamento: 2018,
    genero: "Ação, Drama",
    elenco: ["Ralph Macchio", "William Zabka"],
    duracao: "30min",
    nota_avaliacao: 8.6,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Décadas após o torneio de karatê de 1984, Johnny Lawrence reabre o dojo Cobra Kai. Isso reacende sua rivalidade com Daniel LaRusso, e a vida dos dois e de uma nova geração de lutadores se entrelaçam."
  },
  {
    id: 18,
    titulo: "Arrow",
    tipo: "s",
    fotoThumbnail: "../Imagens/Arrow-NI.jpg",
    ano_lancamento: 2012,
    genero: "Ação, Super-herói",
    elenco: ["Stephen Amell", "Katie Cassidy"],
    duracao: "42min",
    nota_avaliacao: 7.5,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Após ser dado como morto por cinco anos, o bilionário Oliver Queen retorna à sua cidade com uma nova missão: combater o crime como um vigilante encapuzado, usando suas habilidades com arco e flecha para caçar os corruptos."
  },
  {
    id: 19,
    titulo: "Ratched",
    tipo: "s",
    fotoThumbnail: "../Imagens/ratched.webp",
    ano_lancamento: 2020,
    genero: "Drama, Suspense",
    elenco: ["Sarah Paulson", "Finn Wittrock"],
    duracao: "1h",
    nota_avaliacao: 7.3,
    faixa_etaria: "16+",
    indicacoes_premios: [],
    sinopse: "Em 1947, a série explora a origem de Mildred Ratched, a icônica enfermeira do filme 'Um Estranho no Ninho', mostrando sua jornada de uma simples enfermeira a uma figura manipuladora e monstruosa dentro de um hospital psiquiátrico."
  },
  {
    id: 20,
    titulo: "The Witcher",
    tipo: "s",
    fotoThumbnail: "../Imagens/The-Witcher-NI.jpeg",
    ano_lancamento: 2019,
    genero: "Fantasia, Ação",
    elenco: ["Henry Cavill", "Anya Chalotra"],
    duracao: "1h",
    nota_avaliacao: 8.2,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy"],
    sinopse: "Geralt de Rívia, um caçador de monstros solitário, luta para encontrar seu lugar em um mundo onde as pessoas frequentemente se mostram mais perversas do que as bestas. Seu destino se entrelaça com o de uma jovem princesa e uma feiticeira."
  },
];
