export const filmes = [
  {
    id: 1,
    titulo: "Selma",
    slug:"Selma",
    fotoThumbnail: "../Imagens/Filmes-educacionais/SELMA.jpg",
    ano_lancamento: 201,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Histórico",
     elenco: ["David Oyelowo", "Carmen Ejogo", "Tom Wilkinson", "Oprah Winfrey"],
    duracao: "128min",
    nota_avaliacao: 7.5,
    numero_comentarios: 8450,
    faixa_etaria: "12+",
    indicacoes_premios: ["Oscar", "Globo de Ouro", "BAFTA"],
    sinopse: "Acompanhe a inspiradora marcha liderada por Martin Luther King Jr. de Selma a Montgomery, no Alabama, em 1965. O movimento buscava garantir o direito ao voto para a comunidade negra dos Estados Unidos, enfrentando intensa repressão e violência policial, tornando-se um marco fundamental na luta pelos direitos civis."
},
  {
    id: 2,
    titulo: "Mãos Talentosas",
    fotoThumbnail: "../Imagens/Filmes-educacionais/TALENTOSAS.webp",
    ano_lancamento: 2013,
    tipo: "f",
    temporadas: null,
    genero: "Drama, Biografia",
    elenco: ["Cuba Gooding Jr.", "Kimberly Elise", "Aunjanue Ellis"],
    duracao: "86min",
    nota_avaliacao: 7.7,
    numero_comentarios: 6240,
    faixa_etaria: "10+",
    indicacoes_premios: ["Image Awards", "Humanitas Prize"],
    sinopse: "Baseado em uma história real, o filme acompanha a trajetória de Ben Carson, que de uma infância humilde marcada por dificuldades se tornou um dos neurocirurgiões mais renomados do mundo. Sua determinação, fé e dedicação aos estudos transformaram sua vida e inspiraram milhões."
},
  {
  id: 3,
  titulo: "Cidade de Deus",
  fotoThumbnail: "../Imagens/Filmes-educacionais/CIDADE-DE-DEUS.jpg",
  ano_lancamento: 2002,
  tipo: "f",
  temporadas: null,
  genero: "Drama, Crime",
  elenco: ["Alexandre Rodrigues", "Leandro Firmino", "Phellipe Haagensen", "Douglas Silva"],
  duracao: "130min",
  nota_avaliacao: 8.6,
  numero_comentarios: 18950,
  faixa_etaria: "16+",
  indicacoes_premios: ["Oscar", "BAFTA", "Globo de Ouro"],
  sinopse: "Inspirado em fatos reais, o filme retrata a ascensão do crime organizado na comunidade Cidade de Deus, no Rio de Janeiro, entre as décadas de 1960 e 1980. A história é contada pela perspectiva de Buscapé, um jovem que sonha em ser fotógrafo, enquanto acompanha a violência, o tráfico e a luta pela sobrevivência em meio à pobreza."
},
  {
  id: 4,
  titulo: "O Primeiro da Classe",
  slug: "o-primeiro-da-classe",
  fotoThumbnail: "../Imagens/Filmes-educacionais/CLASSE.webp",
  ano_lancamento: 2008,
  tipo: "f",
  temporadas: null,
  genero: "Drama, Biografia",
  elenco: ["James Wolk", "Treat Williams", "Patricia Heaton"],
  duracao: "95min",
  nota_avaliacao: 8.0,
  numero_comentarios: 4120,
  faixa_etaria: "10+",
  indicacoes_premios: ["Humanitas Prize", "Directors Guild of America Awards"],
  sinopse: "Baseado em uma história real, o filme acompanha Brad Cohen, um jovem diagnosticado com síndrome de Tourette que enfrenta preconceito e dificuldades ao longo da vida. Com perseverança e apoio, ele conquista seu sonho de se tornar professor, inspirando alunos e colegas a superar desafios."
},
  {
  id: 5,
  titulo: "Extraordinário",
  slug: "extraordinario",
  fotoThumbnail: "../Imagens/Filmes-educacionais/EXTRAORDINARIO.png",
  ano_lancamento: 2017,
  tipo: "f",
  temporadas: null,
  genero: "Drama, Família",
  elenco: ["Jacob Tremblay", "Julia Roberts", "Owen Wilson", "Izabela Vidovic"],
  duracao: "113min",
  nota_avaliacao: 8.0,
  numero_comentarios: 10230,
  faixa_etaria: "10+",
  indicacoes_premios: ["Critics' Choice Awards", "Art Directors Guild Awards"],
  sinopse: "Auggie Pullman nasceu com uma síndrome genética que causou deformidades faciais e passou por diversas cirurgias. Pela primeira vez frequentando a escola regular, ele precisa lidar com o preconceito e aprender o valor da amizade, da empatia e da aceitação."
},
  {
    id: 6,
    titulo: "Lupin",
    tipo: "s",
    fotoThumbnail: 'public/Imagens/Lupin-NI.jpg',
    ano_lancamento: 2021,
    genero: "Suspense, Crime",
    elenco: ["Omar Sy", "Ludivine Sagnier"],
    duracao: "50min",
    nota_avaliacao: 7.8,
    numero_comentarios: 6400,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Inspirado pelas aventuras de Arsène Lupin, o ladrão de casaca Assane Diop busca vingança pela injustiça cometida contra seu pai por uma família rica. Usando seu carisma e maestria em disfarces, ele executa roubos elaborados."
  },
];

export const filmes2 = [
  {
    id: 7,
    titulo: "Round 6",
    tipo: "s",
    fotoThumbnail: "../Imagens/Round-6-NI.jpg",
    ano_lancamento: 2021,
    genero: "Drama, Suspense",
    elenco: ["Lee Jung-jae", "Park Hae-soo"],
    duracao: "55min",
    nota_avaliacao: 8.1,
    numero_comentarios: 15000,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy"],
    sinopse: "Um grupo de pessoas com dificuldades financeiras é convidado a participar de uma misteriosa competição de sobrevivência. Eles competem em jogos infantis mortais por um prêmio bilionário, onde quem perde é eliminado."
  },
  {
    id: 8,
    titulo: "La Casa de Papel",
    fotoThumbnail: "../Imagens/La-Casa-De-Papel-NI.jpg",
    tipo: "s",
    ano_lancamento: 2017,
    genero: "Ação, Crime",
    elenco: ["Álvaro Morte", "Úrsula Corberó"],
    duracao: "50min",
    nota_avaliacao: 8.3,
    numero_comentarios: 21000,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy Internacional"],
    sinopse: "Um homem misterioso conhecido como 'O Professor' recruta oito pessoas para realizar o maior assalto da história: roubar a Casa da Moeda da Espanha. Enquanto executam o plano, eles precisam lidar com a polícia e reféns."
  },
  {
    id: 9,
    titulo: "Ragnarok",
    fotoThumbnail: "../Imagens/Ragnarok-NI.jpg",
    tipo: "s",
    ano_lancamento: 2020,
    genero: "Fantasia, Drama",
    elenco: ["David Stakston", "Herman Tømmeraas"],
    duracao: "45min",
    nota_avaliacao: 7.5,
    numero_comentarios: 4300,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Em uma cidade norueguesa afetada pela poluição, um jovem descobre que possui os poderes do deus Thor. Ele precisa confrontar uma família de gigantes disfarçados de empresários que está destruindo a cidade."
  },
  {
    id: 11,
    titulo: "Narcos",
    fotoThumbnail: "../Imagens/Narcos-NI.jpg",
    tipo: "s",
    ano_lancamento: 2015,
    genero: "Crime, Drama",
    elenco: ["Wagner Moura", "Pedro Pascal"],
    duracao: "49min",
    nota_avaliacao: 8.8,
    numero_comentarios: 12000,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy"],
    sinopse: "A série narra a história real da ascensão e queda do infame traficante colombiano Pablo Escobar e do Cartel de Medellín, contada a partir da perspectiva de Escobar e dos agentes do DEA que lideraram a missão para capturá-lo."
  },
];

export const filmesNum = [
  {
    id: 13,
    titulo: "The Chosen",
    tipo: "s",
    fotoThumbnail: "../Imagens/The-Chosen-NI.jpg",
    ano_lancamento: 2017,
    genero: "Drama Religioso",
    elenco: ["Jonathan Roumie", "Shahar Isaac"],
    duracao: "50min",
    nota_avaliacao: 9.3,
    numero_comentarios: 7000,
    faixa_etaria: "12+",
    indicacoes_premios: [],
    sinopse: "A série retrata a vida de Jesus Cristo sob a perspectiva das pessoas que o conheceram e seguiram, explorando suas vidas, lutas e a forma como seus encontros com Jesus os transformaram para sempre."
  },
  {
    id: 14,
    titulo: "Lupin",
    tipo: "s",
    fotoThumbnail: "../Imagens/Lupin-NI.jpg",
    ano_lancamento: 2021,
    genero: "Suspense, Crime",
    elenco: ["Omar Sy", "Clotilde Hesme"],
    duracao: "50min",
    nota_avaliacao: 7.8,
    numero_comentarios: 6400,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Inspirado pelas aventuras de Arsène Lupin, o ladrão de casaca Assane Diop busca vingança pela injustiça cometida contra seu pai por uma família rica. Usando seu carisma e maestria em disfarces, ele executa roubos elaborados."
  },
  {
    id: 15,
    titulo: "Stranger Things",
    tipo: "s",
    fotoThumbnail: "../Imagens/stVertical.jpeg",
    ano_lancamento: 2016,
    genero: "Ficção Científica, Terror",
    elenco: ["Millie Bobby Brown", "Finn Wolfhard"],
    duracao: "50min",
    nota_avaliacao: 8.7,
    numero_comentarios: 15230,
    faixa_etaria: "14+",
    indicacoes_premios: ["Emmy"],
    sinopse: "Em uma pequena cidade, um grupo de amigos se envolve em uma série de eventos sobrenaturais quando um garoto desaparece. Eles acabam descobrindo uma misteriosa menina com poderes telecinéticos e revelam experimentos secretos do governo."
  },
  {
    id: 16,
    titulo: "The Good Place",
    fotoThumbnail: "../Imagens/The-Good-Place-NI.webp",
    tipo: "s",
    ano_lancamento: 2016,
    genero: "Comédia, Fantasia",
    elenco: ["Kristen Bell", "Ted Danson"],
    duracao: "22min",
    nota_avaliacao: 8.2,
    numero_comentarios: 5400,
    faixa_etaria: "12+",
    indicacoes_premios: ["Emmy"],
    sinopse: "Após sua morte, Eleanor Shellstrop é enviada por engano para o 'Lugar Bom'. Percebendo que não pertence àquele lugar, ela busca a ajuda de sua alma gêmea para aprender a ser uma pessoa melhor e garantir sua permanência."
  },
  {
    id: 17,
    titulo: "Cobra Kai",
    fotoThumbnail: "../Imagens/Cobra-Kai-NI.jpg",
    tipo: "s",
    ano_lancamento: 2018,
    genero: "Ação, Drama",
    elenco: ["Ralph Macchio", "William Zabka"],
    duracao: "30min",
    nota_avaliacao: 8.6,
    numero_comentarios: 8600,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Décadas após o torneio de karatê de 1984, Johnny Lawrence reabre o dojo Cobra Kai. Isso reacende sua rivalidade com Daniel LaRusso, e a vida dos dois e de uma nova geração de lutadores se entrelaçam."
  },
  {
    id: 18,
    titulo: "Arrow",
    tipo: "s",
    fotoThumbnail: "../Imagens/Arrow-NI.jpg",
    ano_lancamento: 2012,
    genero: "Ação, Super-herói",
    elenco: ["Stephen Amell", "Katie Cassidy"],
    duracao: "42min",
    nota_avaliacao: 7.5,
    numero_comentarios: 9100,
    faixa_etaria: "14+",
    indicacoes_premios: [],
    sinopse: "Após ser dado como morto por cinco anos, o bilionário Oliver Queen retorna à sua cidade com uma nova missão: combater o crime como um vigilante encapuzado, usando suas habilidades com arco e flecha para caçar os corruptos."
  },
  {
    id: 19,
    titulo: "Ratched",
    tipo: "s",
    fotoThumbnail: "../Imagens/ratched.webp",
    ano_lancamento: 2020,
    genero: "Drama, Suspense",
    elenco: ["Sarah Paulson", "Finn Wittrock"],
    duracao: "1h",
    nota_avaliacao: 7.3,
    numero_comentarios: 3200,
    faixa_etaria: "16+",
    indicacoes_premios: [],
    sinopse: "Em 1947, a série explora a origem de Mildred Ratched, a icônica enfermeira do filme 'Um Estranho no Ninho', mostrando sua jornada de uma simples enfermeira a uma figura manipuladora e monstruosa dentro de um hospital psiquiátrico."
  },
  {
    id: 20,
    titulo: "The Witcher",
    tipo: "s",
    fotoThumbnail: "../Imagens/The-Witcher-NI.jpeg",
    ano_lancamento: 2019,
    genero: "Fantasia, Ação",
    elenco: ["Henry Cavill", "Anya Chalotra"],
    duracao: "1h",
    nota_avaliacao: 8.2,
    numero_comentarios: 14500,
    faixa_etaria: "16+",
    indicacoes_premios: ["Emmy"],
    sinopse: "Geralt de Rívia, um caçador de monstros solitário, luta para encontrar seu lugar em um mundo onde as pessoas frequentemente se mostram mais perversas do que as bestas. Seu destino se entrelaça com o de uma jovem princesa e uma feiticeira."
  },
];